/**
 * Generates the CSS and TypeScript token layers from tokens.dtcg.json.
 *
 * Why a script and not Style Dictionary: the source is standard W3C DTCG, so
 * Style Dictionary 4 (or Terrazzo, or Tokens Studio) can be dropped in later
 * without touching the source file. For ~50 tokens and two targets, a
 * dependency would be more moving parts than the 90 lines below.
 *
 *   bun run tokens
 *
 * Outputs (both committed — CI and Vercel build without running this):
 *   src/design/tokens.generated.css  @theme primitives + @theme inline semantics
 *   src/design/tokens.generated.ts   resolved hex for chart props
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'design');
const src = JSON.parse(readFileSync(join(DIR, 'tokens.dtcg.json'), 'utf8'));

/**
 * Walk the DTCG tree, yielding [pathSegments, token] for every node with a $value.
 * `$type` is inherited from the nearest ancestor that declares it, per the DTCG
 * spec — most tokens here get their type from the group, not the leaf.
 */
function* walk(node, path = [], inheritedType) {
  const type = node.$type ?? inheritedType;
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$') || typeof v !== 'object' || v === null) continue;
    if ('$value' in v) yield [[...path, k], { ...v, $type: v.$type ?? type }];
    else yield* walk(v, [...path, k], type);
  }
}

const bySegments = new Map([...walk(src)].map(([p, t]) => [p.join('.'), t]));

/** Resolve DTCG `{a.b.c}` aliases to a literal. Throws on a dangling or cyclic reference. */
function resolve(ref, seen = new Set()) {
  const m = /^\{([^}]+)\}$/.exec(String(ref));
  if (!m) return ref;
  const key = m[1];
  if (seen.has(key)) throw new Error(`cyclic token alias: ${[...seen, key].join(' -> ')}`);
  const target = bySegments.get(key);
  if (!target) throw new Error(`dangling token alias: {${key}}`);
  return resolve(target.$value, new Set([...seen, key]));
}

const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
/** Primitive-relative path (e.g. ['ink','900']) -> `ink-900`. */
const cssName = (segs) => segs.map(kebab).join('-');

// ── Retired: the legacy alias tier ────────────────────────────────────────────
// The pre-token utility names (bg, panel, txt, dim, up, down, violet, …) were a
// staged-migration shim. All call sites are migrated and the aliases are gone.
// `bun run tokens:lint` fails the build if one reappears — Tailwind emits nothing
// for an unknown class, so the regression would otherwise be invisible until
// someone saw black-on-black in prod. Retired names live in scripts/tokens-lint.mjs.

// semantic.<group>.<name> -> the CSS utility stem. `text` becomes `fg` so the
// utility reads `text-fg-primary`, not `text-text-primary`; `border` becomes
// `line` so it reads `border-line-subtle`.
const STEM = { surface: 'surface', border: 'line', text: 'fg', value: 'value', accent: 'accent' };

const primitives = [...walk(src.primitive)].map(([p, t]) => [p, t]);
const semantics = [...walk(src.semantic)].map(([p, t]) => [p, t]);
const components = [...walk(src.component)].map(([p, t]) => [p, t]);

const semName = ([group, ...rest]) => `${STEM[group] ?? group}-${rest.map(kebab).join('-')}`;

// ── CSS ───────────────────────────────────────────────────────────────────────
const banner = `/* GENERATED by scripts/build-tokens.mjs from tokens.dtcg.json — do not edit. */\n`;

const primLines = primitives.map(([p, t]) => {
  const ns = t.$type === 'fontFamily' ? '--font' : '--color';
  const name = t.$type === 'fontFamily' ? p.at(-1) : cssName(p);
  return `  ${ns}-${name}: ${resolve(t.$value)};`;
});

const semLines = semantics.map(([p, t]) => `  --color-${semName(p)}: var(--color-${cssName(findPrimitivePath(t.$value))});`);
const compLines = components.map(([p, t]) => `  --color-${p.map(kebab).join('-')}: var(--color-${cssName(findPrimitivePath(t.$value))});`);

/** A tier-2/3 $value is always an alias; return the referenced primitive's path. */
function findPrimitivePath(value) {
  const m = /^\{([^}]+)\}$/.exec(String(value));
  if (!m) throw new Error(`semantic/component tokens must alias a primitive, got literal: ${value}`);
  let key = m[1];
  // Follow through intermediate aliases until we land in primitive.*
  for (let i = 0; i < 10 && !key.startsWith('primitive.'); i++) {
    const next = /^\{([^}]+)\}$/.exec(String(bySegments.get(key).$value));
    if (!next) break;
    key = next[1];
  }
  if (!key.startsWith('primitive.')) throw new Error(`alias must bottom out in primitive.*, got: ${key}`);
  return key.split('.').slice(1); // drop the `primitive` root — cssName expects a relative path
}

// The shadcn/ui contract, expressed once. Previously duplicated across an
// `@theme inline` block and a `:root` block that had to be kept in sync by hand.
const SHADCN = {
  background: 'surface-base',
  foreground: 'fg-primary',
  card: 'surface-raised',
  'card-foreground': 'fg-primary',
  popover: 'surface-raised',
  'popover-foreground': 'fg-primary',
  primary: 'accent-primary',
  'primary-foreground': 'surface-base',
  secondary: 'surface-overlay',
  'secondary-foreground': 'fg-primary',
  muted: 'surface-sunken',
  'muted-foreground': 'fg-secondary',
  accent: 'accent-primary-surface',
  'accent-foreground': 'accent-primary',
  destructive: 'value-negative',
  'destructive-foreground': 'fg-primary',
  border: 'line-subtle',
  input: 'line-strong',
  ring: 'accent-primary',
};
const shadcnTheme = Object.entries(SHADCN).map(([k, v]) => `  --color-${k}: var(--color-${v});`);
const shadcnRoot = Object.entries(SHADCN).map(([k, v]) => `  --${k}: var(--color-${v});`);

// Tailwind only emits utilities it finds in the source scan. The semantic tier has to ship
// whether or not this app happens to use every name yet — the design system is also consumed
// by the claude.ai/design agent, which composes new markup against the documented vocabulary.
// Without this, a documented class silently resolves to nothing.
const SAFELIST_PREFIXES = ['bg', 'text', 'border', 'ring', 'fill', 'stroke', 'from', 'to'];
const semUtilities = semantics.map(([p]) => semName(p));
const safelist = SAFELIST_PREFIXES.map(
  (pre) => `@source inline("${pre}-{${semUtilities.join(',')}}");`,
).join('\n');

writeFileSync(
  join(DIR, 'tokens.generated.css'),
  `${banner}
/* ── Tier 1: primitives ─────────────────────────────────────────────────────
   Raw values. Prefer a semantic token in components. */
@theme {
${primLines.join('\n')}
}

/* ── Tier 2: semantics + Tier 3: component tokens ───────────────────────────
   \`inline\` because every value here is a reference. */
@theme inline {
${semLines.join('\n')}

${compLines.join('\n')}

  /* shadcn/ui vocabulary — one definition, mirrored into :root below. */
${shadcnTheme.join('\n')}
}

/* shadcn components read the bare custom properties, not the --color-* ones. */
:root {
${shadcnRoot.join('\n')}
  --radius: 0.5rem;
}

/* Ship the whole semantic tier regardless of what this app currently references. */
${safelist}
`,
);

// ── TypeScript ────────────────────────────────────────────────────────────────
// Charts take colours as props. This is what makes "no hardcoded hex" reachable
// in chart code — the one place the rule kept breaking.
function nest(entries) {
  const out = {};
  for (const [p, t] of entries) {
    let cur = out;
    for (const seg of p.slice(0, -1)) cur = cur[seg] ??= {};
    cur[p.at(-1)] = resolve(t.$value);
  }
  return out;
}

const ts = {
  // Fonts come from tier 1: there is no semantic font tier, and SVG/canvas text needs the
  // family as a value the same way charts need a colour as a value. Without this, every
  // Recharts `tick={{ fontFamily }}` hardcodes the stack and drifts from the source.
  font: nest(primitives.filter(([p]) => p[0] === 'font')).font,
  surface: nest(semantics.filter(([p]) => p[0] === 'surface')).surface,
  border: nest(semantics.filter(([p]) => p[0] === 'border')).border,
  text: nest(semantics.filter(([p]) => p[0] === 'text')).text,
  value: nest(semantics.filter(([p]) => p[0] === 'value')).value,
  accent: nest(semantics.filter(([p]) => p[0] === 'accent')).accent,
  chart: nest(components.filter(([p]) => p[0] === 'chart')).chart,
  banner: nest(components.filter(([p]) => p[0] === 'banner')).banner,
};

writeFileSync(
  join(DIR, 'tokens.generated.ts'),
  `${banner}
/**
 * Resolved token values for code that needs a colour or font as a value rather
 * than a class — Recharts/visx props, canvas, inline SVG. Never hardcode a hex
 * or a font stack in a component; import from here.
 */
export const token = ${JSON.stringify(ts, null, 2)} as const;

export type Token = typeof token;
`,
);

const counts = `${primitives.length} primitive, ${semantics.length} semantic, ${components.length} component`;
console.log(`✓ tokens.generated.css + tokens.generated.ts (${counts})`);
