"""gate_money_probe baseline

Revision ID: 0001
Revises:
Create Date: 2026-08-30

The baseline migration (D-13) — the head of the chain every later phase extends.
Hand-written, not autogenerated: no local database exists to run
`alembic revision --autogenerate` against (Docker's daemon is broken on this
machine, Railway's Postgres is private-network-only) — for one table this is the
smaller thing to do, not a workaround. Matches `morai.db.models.GateMoneyProbe`
exactly; read both together before changing either.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None


def upgrade() -> None:
    op.create_table(
        "gate_money_probe",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("amount_usd", sa.Numeric(14, 4), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )


def downgrade() -> None:
    op.drop_table("gate_money_probe")
