"""identity_and_rls

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-31

The identity schema (`users`, `sessions`, `setup_tokens`, `audit_log`,
`gate_user_scoped_probe`), the least-privilege `morai_app` role, its grants,
and the RLS policies that make tenant isolation (AUTH-07) real rather than
decorative (D2-09, `02-RESEARCH.md`). Hand-written, not autogenerated -- no
local database exists to autogenerate against, same as 0001/0002.

All of phase 2's DDL lives in this one revision. Two revisions created in one
wave would share `down_revision = "0002"`, branch the chain, and fail
`alembic upgrade head` on multiple heads.

**Superusers and `BYPASSRLS` roles always bypass RLS, and `FORCE ROW LEVEL
SECURITY` does not change that** -- it only binds the table *owner*
(postgresql.org/docs/current/ddl-rowsecurity.html). Railway's `postgres` role
is inferred to be a superuser; CI's own `POSTGRES_USER`-created role
definitely is (the official Postgres image's own docs: "This variable will
create the specified user with superuser power"). So this migration's very
first statement asserts its own role rather than assuming it, and raises a
named, explanatory error instead of letting a bare `CREATE ROLE` permission
error be the only signal.

Every DDL statement below that isn't an Alembic `op.*` operation runs through
`op.get_bind().execute(sa.text(...))`, with a bind parameter for anything that
takes user-controlled or environment-sourced data. `CREATE ROLE`/`ALTER
ROLE`'s `PASSWORD` clause is a syntactic exception: Postgres's own grammar
only accepts a string *literal* there (`Sconst`), not a query parameter, so a
bind placeholder cannot appear in that position at all -- confirmed against
the grammar, not an oversight. The password is still never Python-interpolated
into SQL text: it is passed as a genuine bind parameter to Postgres's own
`quote_literal()` first, and only the server-escaped result (never the raw
value, and never something built by Python string formatting) is embedded in
the `CREATE`/`ALTER ROLE` statement text. `NN-34`: the password never appears
in any exception message this migration raises.
"""

from __future__ import annotations

import os
from collections.abc import Sequence

import sqlalchemy as sa
from pydantic import TypeAdapter
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)
_GEN_UUID = sa.text("gen_random_uuid()")  # core Postgres since 13; this cluster is 18.

# `Connection.execute(text(...)).scalar_one()` reads as `Any` -- same
# untyped-boundary shape as `api/errors.py`'s `_ErrorLocation`. `TypeAdapter`
# is this project's narrowing at such a boundary (D-06), not `cast`.
_STR: TypeAdapter[str] = TypeAdapter(str)
_BOOL: TypeAdapter[bool] = TypeAdapter(bool)


def _quote_literal(bind: sa.Connection, value: str) -> str:
    """Postgres's own escaping, via a genuine bind parameter to
    `quote_literal()` -- not Python string formatting -- for the one place
    (`CREATE`/`ALTER ROLE ... PASSWORD`) whose grammar admits only a literal,
    never a query parameter."""
    return _STR.validate_python(
        bind.execute(
            sa.text("SELECT quote_literal(:value)"), {"value": value}
        ).scalar_one()
    )


def upgrade() -> None:
    bind = op.get_bind()

    # First statement: assert the connecting role, not assume it (the one-line
    # check 02-RESEARCH.md, commit 128d7a2, says this migration owes before the
    # RLS design below can be trusted).
    is_superuser = _BOOL.validate_python(
        bind.execute(
            sa.text("SELECT rolsuper FROM pg_roles WHERE rolname = current_user")
        ).scalar_one()
    )
    if not is_superuser:
        current_role = _STR.validate_python(
            bind.execute(sa.text("SELECT current_user")).scalar_one()
        )
        raise RuntimeError(
            f"Migration 0003 must run as a Postgres superuser to create the "
            f"morai_app role (NOSUPERUSER NOBYPASSRLS) -- connected as "
            f"{current_role!r}, which pg_roles reports is not one. Creating "
            f"morai_app, and every RLS policy built on top of it, requires "
            f"superuser privilege for this one migration; the web and worker "
            f"processes never need it."
        )

    password = os.environ.get("MORAI_APP_DB_PASSWORD")
    if password is None:
        raise RuntimeError(
            "MORAI_APP_DB_PASSWORD is required to create the morai_app role "
            "and is withheld from this message deliberately -- values are "
            "never rendered (NN-34)."
        )
    quoted_password = _quote_literal(bind, password)

    # CREATE ROLE guarded so a re-run is not an error: check pg_roles first,
    # ALTER ROLE ... WITH PASSWORD if the role already exists.
    role_exists = bind.execute(
        sa.text("SELECT 1 FROM pg_roles WHERE rolname = 'morai_app'")
    ).scalar_one_or_none()
    if role_exists:
        bind.execute(sa.text(f"ALTER ROLE morai_app WITH PASSWORD {quoted_password}"))
    else:
        bind.execute(
            sa.text(
                "CREATE ROLE morai_app WITH LOGIN NOSUPERUSER NOBYPASSRLS "
                f"PASSWORD {quoted_password}"
            )
        )

    op.create_table(
        "users",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("username", sa.String(), nullable=False, unique=True),
        # Nullable: a freshly-created account has no password until its setup
        # link is consumed (AUTH-01/AUTH-02).
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_table(
        "sessions",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("token_hash", sa.String(), nullable=False, unique=True),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_table(
        "setup_tokens",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("token_hash", sa.String(), nullable=False, unique=True),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("reader_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("subject_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )
    op.create_table(
        "gate_user_scoped_probe",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
    )

    # Grants -- named individually per table, never `ALL TABLES IN SCHEMA`, so
    # a future table's access is a deliberate line in its own migration.
    current_db = _STR.validate_python(
        bind.execute(sa.text("SELECT quote_ident(current_database())")).scalar_one()
    )
    bind.execute(sa.text(f"GRANT CONNECT ON DATABASE {current_db} TO morai_app"))
    bind.execute(sa.text("GRANT USAGE ON SCHEMA public TO morai_app"))
    for table_name in (
        "users",
        "sessions",
        "setup_tokens",
        "audit_log",
        "gate_user_scoped_probe",
    ):
        bind.execute(
            sa.text(
                f"GRANT SELECT, INSERT, UPDATE, DELETE ON {table_name} TO morai_app"
            )
        )
    # `get_db_session` now runs the existing Phase 1 money-roundtrip route as
    # morai_app -- without these two grants, tests/test_money_roundtrip.py
    # goes red for a Phase 2 reason (a missing grant, not a broken route).
    bind.execute(sa.text("GRANT SELECT, INSERT ON gate_money_probe TO morai_app"))
    bind.execute(sa.text("GRANT USAGE, SELECT ON gate_money_probe_id_seq TO morai_app"))

    # RLS ENABLE + FORCE on the three tables holding data an identified caller
    # should see only their own slice of. Deliberately NOT on `sessions` and
    # `setup_tokens`: possession of the opaque, 256-bit token IS the
    # authorization for those two, and both are read by a request that has no
    # RLS context yet -- the session lookup is the very thing that establishes
    # it. This is not an oversight; it is the reason those two tables have no
    # policy below.
    for table_name in ("users", "audit_log", "gate_user_scoped_probe"):
        bind.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
        bind.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))

    # `gate_user_scoped_probe`: no admin clause, ever. No table holding
    # user-owned data may gain one (D2-08, 02-RESEARCH.md Pitfall 4) -- this is
    # the phase's strongest correctness requirement, and the reason `users`'
    # policy below is not a template to copy from.
    bind.execute(
        sa.text(
            "CREATE POLICY user_isolation ON gate_user_scoped_probe "
            "FOR ALL "
            "USING (user_id = current_setting('app.current_user_id', true)::uuid) "
            "WITH CHECK (user_id = current_setting('app.current_user_id', true)::uuid)"
        )
    )
    # `users`: the one deliberate exception. This admin clause exists only
    # because AUTH-01/AUTH-05 require the admin to write other users' account
    # rows to issue a setup link or reset a password -- it is not a pattern to
    # copy onto any table holding trading data (D2-08: "an admin read path
    # here would make [Phase 3's encryption boundary] decorative").
    bind.execute(
        sa.text(
            "CREATE POLICY self_or_admin ON users "
            "FOR ALL "
            "USING ("
            "  id = current_setting('app.current_user_id', true)::uuid "
            "  OR current_setting('app.is_admin', true) = 'true'"
            ") "
            "WITH CHECK ("
            "  id = current_setting('app.current_user_id', true)::uuid "
            "  OR current_setting('app.is_admin', true) = 'true'"
            ")"
        )
    )
    # `audit_log`: INSERT-only, no SELECT policy -- the app role can append
    # and cannot read or alter. Nothing in phase 2 reads this table.
    bind.execute(
        sa.text("CREATE POLICY append_only ON audit_log FOR INSERT WITH CHECK (true)")
    )


def downgrade() -> None:
    bind = op.get_bind()

    # Tables (and their policies, dropped for free with the table) first, in
    # reverse dependency order.
    op.drop_table("gate_user_scoped_probe")
    op.drop_table("audit_log")
    op.drop_table("setup_tokens")
    op.drop_table("sessions")
    op.drop_table("users")

    # Then the grants morai_app holds on objects that outlive this revision --
    # DROP ROLE fails while any privilege grant to the role remains anywhere
    # in the database.
    bind.execute(sa.text("REVOKE SELECT, INSERT ON gate_money_probe FROM morai_app"))
    bind.execute(
        sa.text("REVOKE USAGE, SELECT ON gate_money_probe_id_seq FROM morai_app")
    )
    bind.execute(sa.text("REVOKE USAGE ON SCHEMA public FROM morai_app"))
    current_db = _STR.validate_python(
        bind.execute(sa.text("SELECT quote_ident(current_database())")).scalar_one()
    )
    bind.execute(sa.text(f"REVOKE CONNECT ON DATABASE {current_db} FROM morai_app"))

    # The role last, after every grant it holds is gone.
    bind.execute(sa.text("DROP ROLE IF EXISTS morai_app"))
