"""data_key_and_fills

Revision ID: 0007
Revises: 0006
Create Date: 2026-08-31

Lands `user_data_keys` (the per-user wrapped AES-256-GCM data key, CRYPT-01)
and `fills` (the tracer slice of the encrypted ledger schema, CRYPT-02) --
the two tables plan 03-01's tracer task proves end-to-end. `positions`,
`legs` and `events` land in migration 0008 (plan 03-02): two revisions
written in one wave would share `down_revision = "0006"`, branch the chain,
and fail `alembic upgrade head` on multiple heads (D3-19, and this
precedent already stated in 0003's own docstring).

## Plaintext-by-design columns on `fills`, and the query each serves (D3-02,
CRYPT-03)

- `user_id`: the RLS policy predicate (D3-18) and every per-user window
  query -- reconciliation, listing, everything.
- `order_id`, `occ_symbol`: the shared-front-leg order-anchor disambiguation
  query's join and grouping keys (LEDGER-03, NN-11) -- proven against real
  oracle data in 03-RESEARCH.md's Code Examples this phase's research ran.
- `leg_index`: discriminates two `transferItem`s for one symbol inside one
  order sharing an identical `execution_time` -- a raw-payload structural
  possibility this table defends against before it is proven (NN-1: "it
  never varies today is not it can never vary").
- `execution_time`: the reconciliation window predicate, and discriminates
  a partially-filled leg Schwab reports as two separate prints.
- `position_effect`: what LEDGER-02 classifies OPEN/CLOSE from -- the
  broker's own field, not a derived status.
- `side`: compared only to itself by rule 1 of the fill-pairing algorithm
  (salvage/oracle-fixtures.md) and discloses no dollar amount or position
  size on its own. CONTEXT.md's D3-02 plaintext enumeration does not name
  `side` either way; staying plaintext is this plan's own discretion call.
- `key_version`: selects which `user_data_keys` row unwraps this row's
  ciphertext (D3-07).

`quantity` is encrypted (`quantity_ciphertext`/`quantity_nonce`), not
plaintext, per D3-02: it is a position size, and leaving it readable would
leak strategy to a dump-holder for a SQL-grouping convenience Python can do
after decrypt.

## Cipher choice

AES-256-GCM via `cryptography`'s `AESGCM`, per D3-05. GCM-SIV (the
nonce-misuse-resistant variant, same `cryptography` module) was considered
and not adopted -- D3-05 already names AES-256-GCM specifically, and this
project's realistic encryption volume sits roughly 13,000x below NIST SP
800-38D's 2^32-invocation-per-key ceiling for random nonces
(03-RESEARCH.md Pitfall 2), so GCM-SIV's stronger nonce-misuse resistance
buys nothing at this scale.

## Associated-data row-binding format

Every `encrypt_field`/`decrypt_field` call in `morai.ledger.fills` binds to
associated data of the shape:

    "fills:{column}:{user_id}:{order_id}:{occ_symbol}:{leg_index}:{execution_time_micros}"

colon-delimited UTF-8, with `execution_time` rendered as its integer
microsecond epoch (never an ISO string), so no timezone or formatting
difference between write and read can silently break decryption. Fixed
here, once -- changing this format later costs a full re-encryption of
every row, the same cost class as a DEK rotation.

Hand-written, not autogenerated, matching 0001/0003 -- no local database
exists to autogenerate against at the time those were written, and this
migration follows the same convention for consistency.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table(
        "user_data_keys",
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column(
            "key_version",
            sa.SmallInteger(),
            nullable=False,
            server_default=sa.text("1"),
        ),
        sa.Column("wrapped_dek", sa.LargeBinary(), nullable=False),
        sa.Column("wrap_nonce", sa.LargeBinary(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "key_version"),
    )

    op.create_table(
        "fills",
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=False),
        sa.Column("occ_symbol", sa.Text(), nullable=False),
        sa.Column("leg_index", sa.SmallInteger(), nullable=False),
        sa.Column("execution_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("position_effect", sa.Text(), nullable=False),
        sa.Column("side", sa.Text(), nullable=False),
        sa.Column("quantity_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("quantity_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("price_usd_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("price_usd_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "order_id", "occ_symbol", "leg_index", "execution_time"
        ),
    )

    # Grants -- named individually per table, never `ALL TABLES IN SCHEMA`
    # (matching 0003's own discipline). No UPDATE on user_data_keys:
    # re-wrapping is an operator script on the superuser engine, never an
    # app-role write. Fills are immutable; DELETE exists only for account
    # deletion (AUTH-06).
    bind.execute(sa.text("GRANT SELECT, INSERT, DELETE ON user_data_keys TO morai_app"))
    bind.execute(sa.text("GRANT SELECT, INSERT, DELETE ON fills TO morai_app"))

    # RLS ENABLE + FORCE + a user_isolation policy on both tables (D3-18).
    # No admin clause on either table, ever (D2-08, D3-18) --
    # identity/audit.py's own docstring states a data table inheriting
    # `users`' admin clause makes this whole boundary decorative.
    for table_name in ("user_data_keys", "fills"):
        bind.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
        bind.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
        bind.execute(
            sa.text(
                f"CREATE POLICY user_isolation ON {table_name} "
                "FOR ALL "
                "USING (user_id = "
                "current_setting('app.current_user_id', true)::uuid) "
                "WITH CHECK (user_id = "
                "current_setting('app.current_user_id', true)::uuid)"
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(sa.text("REVOKE SELECT, INSERT, DELETE ON fills FROM morai_app"))
    bind.execute(
        sa.text("REVOKE SELECT, INSERT, DELETE ON user_data_keys FROM morai_app")
    )
    op.drop_table("fills")
    op.drop_table("user_data_keys")
