"""positions_legs_events

Revision ID: 0008
Revises: 0007
Create Date: 2026-08-31

Lands `positions`, `legs` and `events` -- the four-table schema criterion 6
names (with `fills`, migration 0007). Hand-written, not autogenerated,
matching every prior revision. `down_revision = "0007"` -- 0001 through
0007 are applied and never edited in place (D3-19).

## Plaintext-by-design columns, and the query each serves (D3-02, CRYPT-03)

`positions` carries no encrypted columns at all -- it is purely the
aggregate a `leg`/`event` groups under.

- `positions.user_id` / `legs.user_id` / `events.user_id`: the RLS policy
  predicate (D3-18) on each table independently. `legs.user_id` is
  denormalized from `positions` deliberately, so its own policy evaluates
  without a join to `positions` -- matching every other user-scoped table
  in this schema rather than inventing a join-based policy this codebase
  has never used.
- `legs.occ_symbol`, `legs.leg_role`: the shared-front-leg disambiguation
  query's join and grouping keys (LEDGER-03, NN-11), proven against real
  oracle data in 03-RESEARCH.md's Code Examples.
- `legs.root`: the settlement-style discriminator per leg (`SPX` AM vs
  `SPXW` PM, analyzer-and-journal-spec.md Sec 5.4) -- LEDGER-07 needs it
  per leg because a PM-settled front and an AM-settled back can coexist
  inside one position.
- `events.event_type`: the reconciliation window query's own selector and
  the `roll_has_both_legs` CHECK's operand.
- `events.event_time`: the window predicate (D3-02, D3-04) -- the sum
  itself happens in Python after decrypt, never in SQL.
- `events.position_id`: the join key the reconciliation window query walks.
- `events.fill_ids_hash`: a join key making event re-derivation idempotent
  (LEDGER-09) -- nullable because a SETTLEMENT event fires from a
  position's own expiration date with no fill behind it at all
  (analyzer-and-journal-spec.md Sec 5.4), not from a fill set to hash.
- `events.key_version`: selects which `user_data_keys` row unwraps this
  row's ciphertext (D3-07).
- `positions.opened_at`/`closed_at`: ordering and window columns. No
  stored status column -- a position's closed state is derived from net
  quantity per leg (LEDGER-05); a status column is the exact thing that
  made calendar `65aac62e` report open after its real close order fully
  unwound both legs.

`events.open_debit_usd_ciphertext`/`close_credit_usd_ciphertext` (and
their adjacent nonce columns) are the two halves of a compound ROLL event,
kept split per D3-01/D3-12 -- the `_usd` unit suffix survives onto the
`bytea` columns because the unit is a property of the value, not of its
storage type.

## The `roll_has_both_legs` CHECK constraint -- what it catches, and what it
cannot (D3-09, LEDGER-04, criterion 4)

    CHECK (event_type <> 'ROLL' OR (
        open_debit_usd_ciphertext IS NOT NULL
        AND close_credit_usd_ciphertext IS NOT NULL
    ))

This is the code class that cost v1 -$319,850: a compound event netted
into one number, recompute needing the two components separately and
finding only one. The amounts are encrypted `bytea` -- Postgres can never
decrypt them, so this constraint can only test **presence**, never a
numeric relationship. What it catches: a ROLL row silently missing one of
its two amount ciphertexts, regardless of which caller attempts the
insert -- proven in `tests/ledger/test_roll_check_constraint.py` via raw
SQL on a connection that never touches application code. What it does
**not**, and structurally cannot, catch: whether the decrypted value
inside either ciphertext is the correct, un-netted figure. Semantic
correctness is the single write path's job (`insert_events`, Task 3) and
the 13-calendar oracle's (Phase 5) -- never a `CHECK`'s.

`events.event_type` is separately constrained to the four known values:

    CHECK (event_type IN ('OPEN', 'CLOSE', 'ROLL', 'SETTLEMENT'))

## Associated-data row-binding format

`morai.ledger.events`'s `encrypt_field`/`decrypt_field` calls bind to
associated data of the shape:

    "events:{column}:{event_id}"

colon-delimited UTF-8, keyed on the row's own `id` rather than a composite
key (unlike `fills`, `events` has a single-column UUID primary key).
Fixed here, once -- changing this format later costs a full re-encryption
of every row, the same cost class as a DEK rotation.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)
_GEN_UUID = sa.text("gen_random_uuid()")  # core Postgres since 13; this cluster is 18.

_NEW_TABLES = ("positions", "legs", "events")


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table(
        "positions",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    op.create_table(
        "legs",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("position_id", _UUID, sa.ForeignKey("positions.id"), nullable=False),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("leg_role", sa.Text(), nullable=False),
        sa.Column("occ_symbol", sa.Text(), nullable=False),
        sa.Column("root", sa.Text(), nullable=False),
        sa.UniqueConstraint(
            "position_id", "leg_role", name="legs_position_id_leg_role_key"
        ),
    )

    op.create_table(
        "events",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("position_id", _UUID, sa.ForeignKey("positions.id"), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("fill_ids_hash", sa.Text(), nullable=True),
        sa.Column("open_debit_usd_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("open_debit_usd_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("close_credit_usd_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("close_credit_usd_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_type IN ('OPEN', 'CLOSE', 'ROLL', 'SETTLEMENT')",
            name="events_event_type_check",
        ),
        sa.CheckConstraint(
            "event_type <> 'ROLL' OR ("
            "open_debit_usd_ciphertext IS NOT NULL "
            "AND close_credit_usd_ciphertext IS NOT NULL"
            ")",
            name="roll_has_both_legs",
        ),
    )

    # Grants -- named individually per table, never `ALL TABLES IN SCHEMA`
    # (matching 0003/0007's own discipline). No UPDATE on any of the three:
    # nothing in this phase updates a row, and a grant is added by the
    # phase that needs it (the narrowing Phase 2's WR-05 fix established).
    for table_name in _NEW_TABLES:
        bind.execute(
            sa.text(f"GRANT SELECT, INSERT, DELETE ON {table_name} TO morai_app")
        )

    # RLS ENABLE + FORCE + a user_isolation policy on all three (D3-18). No
    # admin clause on any of them, ever (D2-08, D3-18) --
    # identity/audit.py's own docstring states a data table inheriting
    # `users`' admin clause makes this whole encryption boundary decorative.
    for table_name in _NEW_TABLES:
        bind.execute(sa.text(f"ALTER TABLE {table_name} ENABLE ROW LEVEL SECURITY"))
        bind.execute(sa.text(f"ALTER TABLE {table_name} FORCE ROW LEVEL SECURITY"))
        bind.execute(
            sa.text(
                f"CREATE POLICY user_isolation ON {table_name} "
                "FOR ALL "
                "USING (user_id = "
                "current_setting('app.current_user_id', true)::uuid) "
                "WITH CHECK (user_id = "
                "current_setting('app.current_user_id', true)::uuid)"
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    for table_name in reversed(_NEW_TABLES):
        bind.execute(
            sa.text(f"REVOKE SELECT, INSERT, DELETE ON {table_name} FROM morai_app")
        )
    # Reverse dependency order: events references positions, legs
    # references positions.
    op.drop_table("events")
    op.drop_table("legs")
    op.drop_table("positions")
