"""schwab_connections

Revision ID: 0010
Revises: 0009
Create Date: 2026-08-31

Lands `schwab_connections` (CONN-01..CONN-07). Hand-written, not
autogenerated, matching every prior revision. `down_revision = "0009"` --
0001 through 0009 are applied and never edited in place (D4-21).

`user_id` is the primary key -- one row per user by construction, not by a
runtime uniqueness check. That is what makes D4-09's repair-in-place natural
(an `UPDATE ... WHERE user_id = :uid`, falling back to `INSERT` only when
`rowcount` is zero) rather than something a CHECK or a unique index has to
enforce.

## Plaintext-by-design columns, and why (D4-11, D3-02-style call)

- `user_id`: the RLS policy predicate (D4-19) and the single-row-per-user
  lookup every route in this plan makes.
- `key_version`: selects which `user_data_keys` row unwraps this row's two
  ciphertexts (D3-07, D4-11 -- the same DEK domain Phase 3 already
  provisions, not a second key domain).
- `token_created_at`: `schwab-py`'s own `TokenMetadata.creation_timestamp`,
  explicitly never touched by an ordinary refresh (verified against the real
  1.5.1 wheel this phase's research read). Connection metadata, not trading
  data -- the same plaintext-timestamp precedent `positions.opened_at`
  already sets, and it is the anchor `derive_connection_health` reads
  (D4-12): a stored health column would be a second writer for something
  derivable.
- `last_synced_at`: CONN-07, D4-16. NULL until a genuinely successful sync
  writes it -- this phase leaves it NULL throughout (04-VALIDATION.md's own
  scope decision); the column exists and is queryable, nothing writes it yet.
- `reauth_notified_at`: D4-13. Records that a notification is due; delivery
  is a later phase, so nothing in this phase's routes ever reads it back.
- `created_at`: ordinary row-provenance timestamp, matching every other
  table in this schema.

`account_hash_ciphertext`/`account_hash_nonce` and
`token_ciphertext`/`token_nonce` are the two encrypted values (D4-11,
D4-17) -- the account hash is resolved once at connect time from
`get_account_numbers()` and never re-resolved; the token is the vendor's
own OAuth token, wrapped under the connecting user's existing Phase 3 DEK,
never a separate key domain.

## Grants and RLS (D4-19)

Unlike `fills`/`events`/`positions` (migrations 0007/0008), this table
genuinely needs `UPDATE` -- D4-09's repair-in-place is the requirement
here, not an ORM artifact those tables never had. `ENABLE`+`FORCE` RLS, one
`user_isolation` policy with both `USING` and `WITH CHECK`, no admin
clause, ever -- matching 0007/0008's shape exactly.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table(
        "schwab_connections",
        sa.Column(
            "user_id", _UUID, sa.ForeignKey("users.id"), primary_key=True
        ),
        sa.Column("account_hash_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("account_hash_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("token_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("token_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column("token_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reauth_notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
    )

    # Unlike fills/events/positions, this table genuinely needs UPDATE --
    # D4-09's repair-in-place is the requirement, not an ORM artifact.
    bind.execute(
        sa.text(
            "GRANT SELECT, INSERT, UPDATE, DELETE ON schwab_connections TO morai_app"
        )
    )

    bind.execute(
        sa.text("ALTER TABLE schwab_connections ENABLE ROW LEVEL SECURITY")
    )
    bind.execute(sa.text("ALTER TABLE schwab_connections FORCE ROW LEVEL SECURITY"))
    bind.execute(
        sa.text(
            "CREATE POLICY user_isolation ON schwab_connections "
            "FOR ALL "
            "USING (user_id = "
            "current_setting('app.current_user_id', true)::uuid) "
            "WITH CHECK (user_id = "
            "current_setting('app.current_user_id', true)::uuid)"
        )
    )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text(
            "REVOKE SELECT, INSERT, UPDATE, DELETE ON schwab_connections "
            "FROM morai_app"
        )
    )
    op.drop_table("schwab_connections")
