"""broker_transactions

Revision ID: 0011
Revises: 0010
Create Date: 2026-09-01

Lands `broker_transactions` (D6-02, INGEST-02). Hand-written, matching every
prior revision. `down_revision = "0010"` -- 0001 through 0010 are applied
and never edited in place (D4-21's own precedent).

## Natural key, not a hashed surrogate (`NN-1`, WR-A3)

Composite primary key: `(user_id, activity_id)`. `salvage/invariants.md`'s
`syncTransactions.property.test.ts` entry records the real production bug
this design avoids: v1's `hexToUuid` synthesized a version-5 UUID from
`(activityId, legIndex)` and dropped input hex nibble 12, so two distinct
real transactions collided on one identifier and the old `fills.id`
primary key's `onConflictDoNothing` then silently dropped the second real
fill. This table uses the natural key directly. A hashed surrogate key is
forbidden here for that reason.

## Bind-parameter arithmetic (`NN-5`, `OPS-05`, derived per
`salvage/measured-constants.md`'s own discipline -- never copy-pasted)

Nine columns: `user_id`, `activity_id`, `transaction_type`,
`transaction_time`, `order_id`, `raw_ciphertext`, `raw_nonce`,
`key_version`, `created_at`. `floor(65534 / 9) = 7281` -- the project's
existing 2,000-row chunk (`_CHUNK_SIZE` in
`morai.ingest.broker_transactions`) sits at roughly a quarter of that
ceiling, with room to spare.

## Plaintext-by-design columns, and the query each serves (D3-02-style call)

- `user_id`: the RLS policy predicate and every per-user window query.
- `activity_id`: half the primary key and the idempotency conflict target.
- `transaction_time`: the window Phase 9's reconciliation compares over.
- `transaction_type`: lets a reader tell a trade from a cash movement
  without decrypting anything.
- `order_id`: the join key back to `fills`. Nullable -- absent on every
  non-trade element, and a gap is `NULL`, never an empty string (`NN-16`).
- `key_version`: selects which `user_data_keys` row unwraps this row's
  ciphertext.

The vendor's whole raw element is encrypted (`raw_ciphertext`/`raw_nonce`)
because it carries money and position size -- under the same per-user DEK
Phase 3 already provisions, never a second key domain.

## Grants and RLS (`V092`)

`GRANT SELECT, INSERT, DELETE` only -- deliberately no `UPDATE`: this table
is immutable, and withholding the privilege is the cheapest possible
enforcement. `ENABLE`+`FORCE` RLS with a `FOR ALL` `user_isolation` policy,
copied from 0007's body. `FOR ALL` is required, not stylistic: `V092`
records that an INSERT-only policy set (no `SELECT` clause) breaks any
statement carrying an implicit or explicit read-back clause, and this
table's insert path uses a `RETURNING` clause for its landed-count.

Hand-written, not autogenerated, matching every prior revision.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0011"
down_revision: str | None = "0010"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table(
        "broker_transactions",
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("activity_id", sa.Text(), nullable=False),
        sa.Column("transaction_type", sa.Text(), nullable=False),
        sa.Column("transaction_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("order_id", sa.Text(), nullable=True),
        sa.Column("raw_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("raw_nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", "activity_id"),
    )

    # No UPDATE -- immutable table, withholding the privilege is the
    # cheapest possible enforcement (D6-02).
    bind.execute(
        sa.text("GRANT SELECT, INSERT, DELETE ON broker_transactions TO morai_app")
    )

    # FOR ALL, not INSERT-only -- see this migration's own docstring (V092).
    bind.execute(sa.text("ALTER TABLE broker_transactions ENABLE ROW LEVEL SECURITY"))
    bind.execute(sa.text("ALTER TABLE broker_transactions FORCE ROW LEVEL SECURITY"))
    bind.execute(
        sa.text(
            "CREATE POLICY user_isolation ON broker_transactions "
            "FOR ALL "
            "USING (user_id = "
            "current_setting('app.current_user_id', true)::uuid) "
            "WITH CHECK (user_id = "
            "current_setting('app.current_user_id', true)::uuid)"
        )
    )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text("REVOKE SELECT, INSERT, DELETE ON broker_transactions FROM morai_app")
    )
    op.drop_table("broker_transactions")
