"""sync_runs

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-01

Lands `sync_runs` (INGEST-06). Hand-written, not autogenerated, matching
every prior revision. `down_revision = "0011"` -- 0001 through 0011 are
applied and never edited in place (D4-21's own precedent).

## What this table is for, and the two subtleties it exists to close

A `sync_user` run that succeeds leaves one row naming when it ran, how it
was triggered, and how much landed. A run that raises still leaves one row
-- with a classified error code and both landed counts `NULL` rather than
`0` -- and that row is written on a **second, fresh session** opened after
the ingest session's own rollback, precisely so the failure record does not
roll back with the transaction that failed (06-03-PLAN.md's own framing).
The worker wrapper (`morai.worker.app.sync_user_task`) is where that
two-session split lives; this migration only lands the table it writes
into.

## Plaintext-by-design, and the reason stated explicitly (D3-02-style call)

Nothing on this table is encrypted. A run's timings, its status, its
classified error code and its row counts are operational metadata about a
cycle, not trading data -- the same call `schwab_connections.token_created_at`
already makes. The row counts are the one debatable case: a count is weakly
correlated with trading activity. Recorded here as a judgement, not left
implicit, so a later reader can overturn it on purpose.

- `user_id`: the RLS policy predicate and the one query this table serves,
  most-recent-first for one user.
- `started_at`/`finished_at`: the window a sync ran over -- `started_at` is
  also what `schwab_connections.last_synced_at` is set to on success (the
  start, not the finish, per 06-03-PLAN.md's own reasoning: a fill executed
  while the vendor call was in flight falls inside the next window rather
  than between two).
- `trigger`: `scheduled` or `manual` -- how the run was started, and the
  only thing `POST /schwab/sync` (task 2) adds to the payload the periodic
  fan-out already produces.
- `status`: `succeeded` or `failed`.
- `fills_landed`/`broker_transactions_landed`: nullable on purpose. A
  failed run landed an unknown number of rows, not zero -- writing zero
  would make a broken cycle indistinguishable from an empty one (`NN-16`
  applied to a count rather than a price).
- `error_code`: nullable, populated only on failure, and never derived from
  an exception's own text (`classify_sync_error`,
  `morai.ingest.sync_runs`) -- a vendor error can carry a token, a full
  response body or a redirect URL, and every one of those is
  bearer-equivalent (`NN-34`).

Two `CHECK` constraints restrict `trigger` and `status` to the values this
phase defines -- a database constraint, so a later caller inventing a third
value cannot store it silently, the same discipline the netted-ROLL `CHECK`
in migration 0008 already sets.

Index on `(user_id, started_at DESC)` -- the sync-run read is always
most-recent-first for one user, and it is the only query this table serves.

## Grants and RLS (`V092`)

`GRANT SELECT, INSERT, DELETE` only -- no `UPDATE`: a run record is written
once, when the run ends. `ENABLE`+`FORCE` RLS with a `FOR ALL`
`user_isolation` policy, copied from 0011's body. `FOR ALL`, not
INSERT-only, for `V092`'s reason (an INSERT-only policy has no `SELECT` to
permit the implicit `RETURNING` this project's own insert helpers append)
and because the user reads these rows back (`GET /schwab/sync-runs`, task
3).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)
_GEN_UUID = sa.text("gen_random_uuid()")  # core Postgres since 13; this cluster is 18.


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table(
        "sync_runs",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("fills_landed", sa.Integer(), nullable=True),
        sa.Column("broker_transactions_landed", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trigger IN ('scheduled', 'manual')",
            name="sync_runs_trigger_check",
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed')",
            name="sync_runs_status_check",
        ),
    )

    op.create_index(
        "ix_sync_runs_user_id_started_at",
        "sync_runs",
        ["user_id", sa.text("started_at DESC")],
    )

    # No UPDATE -- a run record is written once, when the run ends (D6-02's
    # identical reasoning for broker_transactions' own no-UPDATE grant).
    bind.execute(sa.text("GRANT SELECT, INSERT, DELETE ON sync_runs TO morai_app"))

    # FOR ALL, not INSERT-only -- see this migration's own docstring (V092).
    bind.execute(sa.text("ALTER TABLE sync_runs ENABLE ROW LEVEL SECURITY"))
    bind.execute(sa.text("ALTER TABLE sync_runs FORCE ROW LEVEL SECURITY"))
    bind.execute(
        sa.text(
            "CREATE POLICY user_isolation ON sync_runs "
            "FOR ALL "
            "USING (user_id = "
            "current_setting('app.current_user_id', true)::uuid) "
            "WITH CHECK (user_id = "
            "current_setting('app.current_user_id', true)::uuid)"
        )
    )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(sa.text("REVOKE SELECT, INSERT, DELETE ON sync_runs FROM morai_app"))
    op.drop_table("sync_runs")
