"""snapshot_capture

Revision ID: 0015
Revises: 0014
Create Date: 2026-09-01

Lands three tables for Phase 8's snapshot capture (SNAP-01, SNAP-02).
Hand-written, not autogenerated, matching every prior revision.
`down_revision = "0014"` -- 0001 through 0014 are applied and never edited
in place (D4-21's own precedent).

## Two layers, raw and derived (D8-01, D8-04, L039)

`snapshot_observations` is the raw layer: the vendor's whole `get_quotes`
response element for one leg at one slot, stored verbatim and encrypted.
`snapshot_marks` is derived from it: the parsed mark and spot. Two tables,
not one with a discriminator, so the repair path (plan 08-04) can rebuild
`snapshot_marks` from `snapshot_observations` with a plain re-parse and
re-upsert, never a second vendor call -- the same argument Phase 6 already
made for `broker_transactions` vs `fills`.

## The composite key is `(leg_id, slot_time)`, never `occ_symbol` (NN-1,
Pitfall 4, 08-RESEARCH.md)

A trader can re-enter a closed contract in a new position; two different
`Leg` rows can share one `occ_symbol` over this system's lifetime. `leg_id`
is a UUID, globally unique per leg, and already functionally determines
both `user_id` and `root` through the existing foreign-key chain (Phase 7)
-- neither column adds discrimination the key does not already have, so
neither is part of it. Keying by `occ_symbol` instead would silently
collide two positions' history onto one key, the same shape of bug
`L001`/`L002` catalog at length with a different discriminator missing.

## `gap_reason` carries all four values from the start (D8-14, Pitfall 2,
08-RESEARCH.md's own finding on `PeriodicDeferrer.MAX_DELAY`)

`no_market_data` is the only value this plan's own writer produces.
`connection_expired` is `D8-14`'s SNAP-05 gap, owned by plan 08-02.
`vendor_error` is the orchestrator's resolved answer to research open
question A3, also owned by 08-02. `slot_not_captured` is what plan 08-03
writes for a slot Procrastinate's own worker never fired a job for at all
-- a worker down more than ten minutes across a slot boundary silently
drops that slot's job entirely (`PeriodicDeferrer.MAX_DELAY`, read directly
from the installed `procrastinate` 3.9.0 source this phase). Pinning all
four now, in one `CHECK`, means neither later plan has to `ALTER` a
populated table to widen a vocabulary this migration could name for free.

## The gap-xor-payload `CHECK` (D8-09, L041)

Either `gap_reason` is `NULL` and every payload column is `NOT NULL`, or
`gap_reason` is set and every payload column is `NULL`. This is "is this
row a gap" pinned once, at the database level, so no read site has to
re-derive the same predicate from a sentinel value it might get wrong --
`L041`'s own lesson, applied here as a `CHECK` rather than left as a
convention. On `snapshot_marks` the spot pair is deliberately outside the
"real row" branch: a real mark whose payload carried a mark but no
underlying price is a real mark with an honest missing spot, and the
`CHECK` must not force a value there (`NN-16`).

## The asymmetric upsert needs `UPDATE`, unlike every prior append-only
table this schema has granted (D8-10)

`sync_runs` and `broker_transactions` grant no `UPDATE` -- each is written
once, or never touched by a second write path. `snapshot_observations` and
`snapshot_marks` are different: their own `ON CONFLICT (leg_id, slot_time)
DO UPDATE ... WHERE` clause (plan 08-01's own writers) is genuinely an
`UPDATE` path -- a later real observation heals an earlier gap, and a
later, corrected observation from the repair path may replace an earlier
one. Withholding `UPDATE` here would not be "the cheapest possible
enforcement" the way it is for an immutable table; it would break the
phase's own reason to exist.

## `snapshot_runs` mirrors `sync_runs` exactly, table only (D8-15, L042)

Same two `CHECK`s (`trigger`, `status`), same no-`UPDATE` grant -- a run
record is written once, when the run ends. No unique constraint on
`(user_id, slot_time)`: a repair run legitimately produces a second row for
a slot already captured, and this table's whole job is telling those two
runs apart, not collapsing them. This migration lands the table only; its
writer is plan 08-04.

## Grants and RLS (`V092`)

`GRANT SELECT, INSERT, UPDATE, DELETE` on the two encrypted tables (the
`UPDATE` reasoning above); `GRANT SELECT, INSERT, DELETE` on
`snapshot_runs`, matching `sync_runs`. `ENABLE`+`FORCE` RLS with a
`FOR ALL user_isolation` policy on all three, copied from 0012's body --
`FOR ALL`, not INSERT-only, for `V092`'s reason.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0015"
down_revision: str | None = "0014"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)
_GEN_UUID = sa.text("gen_random_uuid()")  # core Postgres since 13; this cluster is 18.

_GAP_REASON_VALUES = (
    "no_market_data",
    "connection_expired",
    "vendor_error",
    "slot_not_captured",
)


def _gap_reason_check_sql() -> str:
    values = ", ".join(f"'{value}'" for value in _GAP_REASON_VALUES)
    return f"gap_reason IN ({values})"


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table(
        "snapshot_observations",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("leg_id", _UUID, sa.ForeignKey("legs.id"), nullable=False),
        sa.Column("slot_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gap_reason", sa.Text(), nullable=True),
        sa.Column("raw_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("raw_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            _gap_reason_check_sql(),
            name="snapshot_observations_gap_reason_check",
        ),
        sa.CheckConstraint(
            "(gap_reason IS NULL AND raw_ciphertext IS NOT NULL "
            "AND raw_nonce IS NOT NULL AND key_version IS NOT NULL) "
            "OR (gap_reason IS NOT NULL AND raw_ciphertext IS NULL "
            "AND raw_nonce IS NULL AND key_version IS NULL)",
            name="snapshot_observations_gap_xor_payload_check",
        ),
        sa.UniqueConstraint(
            "leg_id", "slot_time", name="snapshot_observations_leg_slot_key"
        ),
    )
    op.create_index(
        "ix_snapshot_observations_user_id_slot_time",
        "snapshot_observations",
        ["user_id", sa.text("slot_time DESC")],
    )

    op.create_table(
        "snapshot_marks",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("leg_id", _UUID, sa.ForeignKey("legs.id"), nullable=False),
        sa.Column("slot_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gap_reason", sa.Text(), nullable=True),
        sa.Column("mark_usd_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("mark_usd_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("spot_usd_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("spot_usd_nonce", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            _gap_reason_check_sql(),
            name="snapshot_marks_gap_reason_check",
        ),
        sa.CheckConstraint(
            "(gap_reason IS NULL AND mark_usd_ciphertext IS NOT NULL "
            "AND mark_usd_nonce IS NOT NULL AND key_version IS NOT NULL) "
            "OR (gap_reason IS NOT NULL AND mark_usd_ciphertext IS NULL "
            "AND mark_usd_nonce IS NULL AND spot_usd_ciphertext IS NULL "
            "AND spot_usd_nonce IS NULL AND key_version IS NULL)",
            name="snapshot_marks_gap_xor_mark_check",
        ),
        sa.UniqueConstraint("leg_id", "slot_time", name="snapshot_marks_leg_slot_key"),
    )
    op.create_index(
        "ix_snapshot_marks_user_id_slot_time",
        "snapshot_marks",
        ["user_id", sa.text("slot_time DESC")],
    )

    op.create_table(
        "snapshot_runs",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("slot_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("legs_attempted", sa.Integer(), nullable=True),
        sa.Column("marks_written", sa.Integer(), nullable=True),
        sa.Column("gaps_by_reason", postgresql.JSONB(), nullable=True),
        sa.Column("error_code", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "trigger IN ('scheduled', 'manual')",
            name="snapshot_runs_trigger_check",
        ),
        sa.CheckConstraint(
            "status IN ('succeeded', 'failed')",
            name="snapshot_runs_status_check",
        ),
    )
    op.create_index(
        "ix_snapshot_runs_user_id_slot_time",
        "snapshot_runs",
        ["user_id", sa.text("slot_time DESC")],
    )

    # UPDATE is required here, unlike sync_runs/broker_transactions -- this
    # table's own asymmetric upsert (D8-10) IS an UPDATE path, not an
    # append-only or DO-NOTHING one.
    bind.execute(
        sa.text(
            "GRANT SELECT, INSERT, UPDATE, DELETE ON snapshot_observations "
            "TO morai_app"
        )
    )
    bind.execute(
        sa.text("GRANT SELECT, INSERT, UPDATE, DELETE ON snapshot_marks TO morai_app")
    )
    # No UPDATE -- a run record is written once, when the run ends, matching
    # sync_runs' own identical grant.
    bind.execute(sa.text("GRANT SELECT, INSERT, DELETE ON snapshot_runs TO morai_app"))

    for table in ("snapshot_observations", "snapshot_marks", "snapshot_runs"):
        bind.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
        bind.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
        bind.execute(
            sa.text(
                f"CREATE POLICY user_isolation ON {table} "
                "FOR ALL "
                "USING (user_id = "
                "current_setting('app.current_user_id', true)::uuid) "
                "WITH CHECK (user_id = "
                "current_setting('app.current_user_id', true)::uuid)"
            )
        )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text(
            "REVOKE SELECT, INSERT, UPDATE, DELETE ON snapshot_observations "
            "FROM morai_app"
        )
    )
    bind.execute(
        sa.text(
            "REVOKE SELECT, INSERT, UPDATE, DELETE ON snapshot_marks FROM morai_app"
        )
    )
    bind.execute(
        sa.text("REVOKE SELECT, INSERT, DELETE ON snapshot_runs FROM morai_app")
    )
    op.drop_table("snapshot_runs")
    op.drop_table("snapshot_marks")
    op.drop_table("snapshot_observations")
