"""reconciliation_runs

Revision ID: 0016
Revises: 0015
Create Date: 2026-09-01

Lands `reconciliation_runs` for Phase 9 (RECON-01, RECON-02, RECON-03,
RECON-04). Hand-written, not autogenerated, matching every prior revision.
`down_revision = "0015"` -- 0001 through 0015 are applied and never edited
in place.

## What this table is (`D9-13`)

One row per user per settlement-date trading-day window: the window's own
bounds, both sides of the core-value comparison (realised P&L net of
commissions vs. the broker's own cash delta), the signed difference, and a
three-state verdict (`passed`/`failed`/`indeterminate`) with a reason when
the check could not be answered. Criterion 3 requires a failure to name its
window "so the next question is answerable without re-running anything" --
a stored boolean would force a re-run; storing both sides and the signed
difference answers "how far off, and in which direction" from the row
alone.

## `trading_day` is the window's name, plaintext, on purpose

A settlement-date trading day in `America/New_York`, never a UTC-instant
pair -- a reader needs a name they can act on, and a pair of UTC instants
is not that name. `window_start`/`window_end` are recorded alongside it for
`D9-13`, as the bounds a reader can check, never as the membership
predicate -- `ledger/reconciliation.py::trading_day_for` is the only
membership predicate, applied at read time, not at storage time.

## Every money column is `Numeric(14, 4)` and plaintext

Following `sync_runs`' own reasoning for operational metadata about a
cycle, not trading data. Two arguments carry it. First, `D9-13`'s whole
purpose is that "how far off, and in which direction" is answerable from
the stored row alone; a wrapped key in the way defeats that. Second,
`D9-15` requires the status endpoint to be cheap enough to poll before
rendering, and unwrapping a data key on every poll is not that. Every money
column carries the `_usd` suffix because the column name is the only unit
carrier once a value is in the database (`NN-8`) --
`tests/test_money_column_naming.py` walks `Base.metadata` and fails on a
`Numeric` column without one.

## Six constraints, each implementing one decision

`reconciliation_runs_verdict_check` restricts `verdict` to exactly
`passed`, `failed`, `indeterminate` -- `D9-08`'s three states, pinned at
the database level so no writer can invent a fourth.

`reconciliation_runs_reason_check` restricts `reason` to the five
`IndeterminateReason` values, all pinned now rather than widened later on a
populated table, matching `0015_snapshot_capture.py`'s own choice for
`gap_reason`.

`reconciliation_runs_reason_iff_indeterminate_check` asserts `reason` is
non-null exactly when `verdict` is `indeterminate`, and null otherwise --
`D9-08`'s "the causes must be distinguishable" made a database fact: an
`indeterminate` that cannot say why is rejected before it is stored, and a
`failed` needs no reason because the three stored amounts and the signed
difference already describe it completely.

`reconciliation_runs_amounts_present_check` asserts that either `verdict`
is `indeterminate`, or all four money columns are non-null -- the same
gap-xor-payload discipline `0015_snapshot_capture.py` applies, pointed at
this table's own shape: a check that reached a verdict has all its inputs,
and a check that did not is honestly empty rather than zero-filled
(`NN-16`).

`reconciliation_runs_passed_iff_zero_check` asserts that either `verdict`
is `indeterminate`, or the boolean `verdict = 'passed'` equals the boolean
`signed_difference_usd = 0` -- `D9-07` made a database fact rather than
only a code path: a row claiming a pass while carrying a non-zero
difference cannot be stored at all, the one thing a seeded-discrepancy
test could not catch if the writer and the comparator ever disagreed.

`reconciliation_runs_window_order_check` asserts `window_end` is strictly
greater than `window_start`.

## One index, two consumers

`ix_reconciliation_runs_user_id_trading_day_checked_at` on `(user_id,
trading_day, checked_at DESC)` serves both the reopening lookup
(`read_latest_run_for_trading_day`, one window's own most recent row) and
`read_window_verdicts`'s `DISTINCT ON (trading_day) ... ORDER BY
trading_day, checked_at DESC` scan (`D9-15`'s status read) -- exactly this
index's own order, so no second index is needed and neither consumer
should be read alone and tempted to narrow it (see the index comment
below).

No unique constraint on `(user_id, trading_day)`: `D9-03` makes a reopened
window's re-check a new row, exactly the reasoning `0015_snapshot_capture.py`
already records for a repair run producing a second row for a captured
slot.

## Grant and RLS (`V092`)

`GRANT SELECT, INSERT, DELETE`, no `UPDATE` -- matching `sync_runs` exactly.
`D9-03`: a reopening is a new row, so no writer ever needs to modify a
stored verdict. `ENABLE`+`FORCE` RLS with one `FOR ALL user_isolation`
policy, copied from 0015's body verbatim, with no admin clause anywhere in
it (`D2-08`/`D3-18`).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0016"
down_revision: str | None = "0015"
branch_labels: Sequence[str] | str | None = None
depends_on: Sequence[str] | str | None = None

_UUID = postgresql.UUID(as_uuid=True)
_GEN_UUID = sa.text("gen_random_uuid()")  # core Postgres since 13; this cluster is 18.

_VERDICT_VALUES = ("passed", "failed", "indeterminate")

_REASON_VALUES = (
    "cash_amount_unavailable",
    "commission_unavailable",
    "unrecognised_transaction_type",
    "settlement_unpriced",
    "event_amount_unavailable",
)


def _in_list_sql(column: str, values: tuple[str, ...]) -> str:
    rendered = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({rendered})"


def upgrade() -> None:
    bind = op.get_bind()

    op.create_table(
        "reconciliation_runs",
        sa.Column("id", _UUID, primary_key=True, server_default=_GEN_UUID),
        sa.Column("user_id", _UUID, sa.ForeignKey("users.id"), nullable=False),
        sa.Column("trading_day", sa.Date(), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("realised_pnl_usd", sa.Numeric(14, 4), nullable=True),
        sa.Column("commissions_usd", sa.Numeric(14, 4), nullable=True),
        sa.Column("cash_delta_usd", sa.Numeric(14, 4), nullable=True),
        sa.Column("signed_difference_usd", sa.Numeric(14, 4), nullable=True),
        sa.Column("verdict", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("is_reopening", sa.Boolean(), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            _in_list_sql("verdict", _VERDICT_VALUES),
            name="reconciliation_runs_verdict_check",
        ),
        sa.CheckConstraint(
            _in_list_sql("reason", _REASON_VALUES),
            name="reconciliation_runs_reason_check",
        ),
        sa.CheckConstraint(
            "(verdict = 'indeterminate' AND reason IS NOT NULL) "
            "OR (verdict != 'indeterminate' AND reason IS NULL)",
            name="reconciliation_runs_reason_iff_indeterminate_check",
        ),
        sa.CheckConstraint(
            "verdict = 'indeterminate' "
            "OR (realised_pnl_usd IS NOT NULL AND commissions_usd IS NOT NULL "
            "AND cash_delta_usd IS NOT NULL AND signed_difference_usd IS NOT NULL)",
            name="reconciliation_runs_amounts_present_check",
        ),
        sa.CheckConstraint(
            "verdict = 'indeterminate' "
            "OR ((verdict = 'passed') = (signed_difference_usd = 0))",
            name="reconciliation_runs_passed_iff_zero_check",
        ),
        sa.CheckConstraint(
            "window_end > window_start",
            name="reconciliation_runs_window_order_check",
        ),
    )
    op.create_index(
        "ix_reconciliation_runs_user_id_trading_day_checked_at",
        "reconciliation_runs",
        ["user_id", "trading_day", sa.text("checked_at DESC")],
    )
    bind.execute(
        sa.text(
            "COMMENT ON INDEX ix_reconciliation_runs_user_id_trading_day_checked_at "
            "IS 'Two consumers, D9-15: read_latest_run_for_trading_day (the D9-03 "
            "reopening lookup, one window''s latest row) and read_window_verdicts "
            "(DISTINCT ON (trading_day) ORDER BY trading_day, checked_at DESC, "
            "the status read). Reading either consumer alone would tempt "
            "narrowing this index -- it must serve both.'"
        )
    )

    # Append-only, no UPDATE -- matches sync_runs exactly. D9-03: a
    # reopening is a new row, so no writer ever modifies a stored verdict.
    bind.execute(
        sa.text("GRANT SELECT, INSERT, DELETE ON reconciliation_runs TO morai_app")
    )
    bind.execute(
        sa.text("ALTER TABLE reconciliation_runs ENABLE ROW LEVEL SECURITY")
    )
    bind.execute(sa.text("ALTER TABLE reconciliation_runs FORCE ROW LEVEL SECURITY"))
    bind.execute(
        sa.text(
            "CREATE POLICY user_isolation ON reconciliation_runs "
            "FOR ALL "
            "USING (user_id = "
            "current_setting('app.current_user_id', true)::uuid) "
            "WITH CHECK (user_id = "
            "current_setting('app.current_user_id', true)::uuid)"
        )
    )


def downgrade() -> None:
    bind = op.get_bind()
    bind.execute(
        sa.text("REVOKE SELECT, INSERT, DELETE ON reconciliation_runs FROM morai_app")
    )
    op.drop_table("reconciliation_runs")
