/* GENERATED by scripts/build-tokens.mjs from tokens.dtcg.json — do not edit. */

/**
 * Resolved token values for code that needs a colour or font as a value rather
 * than a class — Recharts/visx props, canvas, inline SVG. Never hardcode a hex
 * or a font stack in a component; import from here.
 */
export const token = {
  "font": {
    "display": "'Space Grotesk', system-ui, sans-serif",
    "mono": "'JetBrains Mono', ui-monospace, monospace"
  },
  "surface": {
    "base": "#0a0e14",
    "sunken": "#0c111a",
    "raised": "#0f1521",
    "overlay": "#161d2b",
    "glow": "#141b29"
  },
  "border": {
    "subtle": "#1b2433",
    "strong": "#27313f"
  },
  "text": {
    "primary": "#d6dbe4",
    "secondary": "#7b8696",
    "tertiary": "#566273"
  },
  "value": {
    "positive": "#26a69a",
    "positiveSurface": "#0e3b36",
    "negative": "#ef5350",
    "negativeSurface": "#3e1f23"
  },
  "accent": {
    "primary": "#a78bfa",
    "primarySurface": "#241d40",
    "warning": "#f0b429",
    "info": "#5b9cf6",
    "highlight": "#22d3ee"
  },
  "chart": {
    "grid": "#222839",
    "gridDeep": "#19212e",
    "zeroLine": "#27313f",
    "zeroLineAlt": "#46556a",
    "axisLabel": "#566273",
    "axisLabelAlt": "#67708a",
    "crosshair": "#8a98ad",
    "termLine": "#9aa3b8",
    "gammaPositive": "#26a69a",
    "gammaNegative": "#ef5350",
    "spot": "#5b9cf6",
    "flip": "#f0b429",
    "today": "#a78bfa",
    "expiry": "#7b8696",
    "roll": "#f0b429",
    "compare": "#ffb74d",
    "seriesIndigo": "#6f86c9",
    "seriesPurple": "#7c6fd6",
    "seriesSteel": "#5f93b8"
  },
  "banner": {
    "dangerSurface": "#180f10",
    "dangerBorder": "#5a2b2e",
    "dangerText": "#ef5350",
    "warnSurface": "#231a08",
    "warnBorder": "#5a4a1f",
    "warnText": "#ffb74d"
  }
} as const;

export type Token = typeof token;
